name: Push Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mlutzy/picture-it:latest
      
